---
title: "WritingResultsSession"
author: "JJ"
date: "November 5, 2014"
output: html_document
---


```{r setup, echo=FALSE, cache=FALSE}
##  source: http://yihui.name/knitr/demo/output/
## numbers >= 10^5 will be denoted in scientific notation,
## and rounded to 2 digits 
options(scipen = 1, digits = 2)
```

```{r import library, echo=FALSE, include=FALSE}
library(ggplot2)
library(sjPlot)
library(plyr); library(dplyr)
library(reshape2)
```


```{r import data, echo=FALSE}
grmrec.df.scaled <- read.csv("./CleanData//grmrec.df.scaled.csv")
grmini.df.cleancol <- read.csv("./CleanData//grmini.df.cleancol.csv")
```

```{r t-test, echo=FALSE, include=FALSE}
grmrec.t <- t.test(grmrec.df.scaled$grmrec.pre, grmrec.df.scaled$grmrec.post)
grmreckin.t <- t.test(grmrec.df.scaled$grmrecKin.pre, grmrec.df.scaled$grmrecKin.post)
t.test(grmrec.df.scaled$grmrecNonkin.pre, grmrec.df.scaled$grmrecNonkin.post)
t.test(grmini.df.cleancol$grmini.pre, grmini.df.cleancol$grmini.post)
t.test(grmini.df.cleancol$grminiKin.pre, grmini.df.cleancol$grminiKin.post)
grminiNonkin.t <- t.test(grmini.df.cleancol$grminiNonkin.pre, grmini.df.cleancol$grminiNonkin.post)

```
After social separation, all grooming behaviors decreased (ts >= `r grminiNonkin.t$statistic[[1]]`, ps < 0.05).

```{r data mungling for ggplot2, echo = FALSE, include=FALSE}
grmini.bar.data <- select(grmini.df.cleancol, matches("ID|grmini"), -ConfidencePre, ignore.case = TRUE)
grmrec.bar.data <- select(grmrec.df.scaled, matches("ID|grmrec"), -matches("scaled|Confidence"))


grm.bar.temp <- merge(grmini.bar.data, grmrec.bar.data, by = "ID")
grm.bar <- grm.bar.temp[,-1]
grm.bar.melted <- melt(grm.bar)
var.name.temp <- as.data.frame(strsplit(as.character(grm.bar.melted$variable), "[.]"))

var.name <- as.data.frame(t(var.name.temp))
row.names(var.name) <- 1:nrow(var.name)
as.character(var.name[,2])
as.character(var.name[,2])
grm.bar.df <- data.frame(var.behavior = as.character(var.name[,1]), 
              var.period = as.character(var.name[,2]), 
              Value = grm.bar.melted$value)
```

```{r plot:bar plot, echo=FALSE, fig.height=5, fig.width=8}
levels(grm.bar.df$var.behavior) <- c("grooming", "grooming with kin", "grooming with non-kin", "received grooming", "received grooming with kin", "received grooming with nonkin")
levels(grm.bar.df$var.period) <- c("social separation", "baseline")
grm.bar.df$var.period <- relevel(grm.bar.df$var.period, ref = "baseline")

gp <- ggplot(data = grm.bar.df, aes(y = Value, x = var.period))
barplot <- gp + geom_boxplot() + facet_wrap( ~ var.behavior) + 
  theme_bw() +
  labs(title = "Grooming behavior before and after social separation",
    x = "Period",
       y = "Levels of grooming")

barplot
```

to add to this:
  scatter plots
  regressions results
  
  social network matrices: personality x period --> betweenness/centrality
  


```{r scatter plots:Data mungling, echo=FALSE}
head(grm.bar.temp)
grm.scatter.melted <- melt(grm.bar.temp, id.vars = "ID")
head(grm.scatter.melted)
variable.name.temp <- as.data.frame(strsplit(as.character(grm.scatter.melted$variable), 
                                             "[.]"))
head(variable.name.temp)
variable.name <- as.data.frame(t(variable.name.temp))
row.names(variable.name) <- 1:nrow(variable.name)
as.character(variable.name[,1])
as.character(variable.name[,2])

grm.scatter.temp1 <- data.frame(
  ID = grm.scatter.melted$ID,
  var.behavior = as.character(variable.name[,1]), 
  var.period = as.character(variable.name[,2]), 
  Value = grm.scatter.melted$value)
head(grm.scatter.temp1)

pre.df <- grm.scatter.temp1 %>% 
  filter(var.period == "pre") %>%
  rename(Value.pre = Value) %>%
  select(-var.period)
post.df <- grm.scatter.temp1 %>%
  filter(var.period == "post") %>%
  rename(Value.post = Value) %>%
  select(-var.period)

summary(pre.df)
summary(post.df)
grm.scatter.df <- merge(pre.df, post.df, by = c("ID", "var.behavior"))
head(grm.scatter.df)
```

```{r, echo=FALSE, fig.width=8, fig.height=5}
plot <- ggplot(data = grm.scatter.df, aes(x = Value.pre, y = Value.post))
Scattergrm <- plot + geom_point(shape = 1) + geom_smooth(method = lm) + 
  xlab("Received Grooming before Removal") + ylab("Received Grooming after Removal") +
  theme_classic() + facet_wrap(~ var.behavior) +
  # font sizes
  theme(
    # axis label text size
    text = element_text(size=12), axis.text.x = element_text(vjust=1), 
    
    legend.position=c(0.10, 0.90),
    # legend text size
    legend.text=element_text(size=10),
    
    legend.title=element_text(size=10),
    strip.text = element_text(size = 10))
Scattergrm

```
